name: Atualizar Tabela NBA (Replicante Build)

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-nba:
    runs-on: ubuntu-latest

    steps:
      - name: [SYS] Inicializar repositório local
        uses: actions/checkout@v4

      - name: [SYS] Configurar ambiente de execução (Node.js v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Habilita cache térmico de dependências

      - name: [NET] Injeção de dependências do vetor de scraping
        run: npm install cheerio @supabase/supabase-js dotenv

      - name: [EXEC] Rotina de extração e persistência na base de dados
        run: node scrape.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          
